version: '2.1'
services:
  terminalserver:
    # build: ./
    image: main_ubuntu-xrdp
    # container_name: main_xrdp
    # hostname: terminalserver
    restart: always
    shm_size: 1g
    environment:
       PASSWORDHASH: $$1$$z53Cg/fV$$06o379IvIOxj/ESruVKrG1
       IDLETIME: 11
    ports:
      - "3389:3389"
      - "2222:22"
    volumes:
      - ssh:/etc/ssh/
      - /home/:/home/
      # - /etc/xrdp/:/etc/xrdp/

volumes:
  ssh:
